language: golang

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

env:
  global:
  - GOPATH="$HOME/gopath"
  - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"

install:
  - go get github.com/gin-gonic/gin
  - go get github.com/gin-gonic/contrib/sessions
  - go get github.com/stretchr/testify/assert

script:
  - go test -v
